# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(878, 657)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(10, 20, 541, 271))
        self.toolBox.setObjectName("toolBox")
        self.page_EOM = QtWidgets.QWidget()
        self.page_EOM.setGeometry(QtCore.QRect(0, 0, 541, 209))
        self.page_EOM.setObjectName("page_EOM")
        self.tabWidget = QtWidgets.QTabWidget(self.page_EOM)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 511, 191))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.Channel_Widget_EOM_1 = Channel_Widget(self.tab)
        self.Channel_Widget_EOM_1.setGeometry(QtCore.QRect(10, 0, 480, 150))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel_Widget_EOM_1.sizePolicy().hasHeightForWidth())
        self.Channel_Widget_EOM_1.setSizePolicy(sizePolicy)
        self.Channel_Widget_EOM_1.setMaximumSize(QtCore.QSize(500, 150))
        self.Channel_Widget_EOM_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Channel_Widget_EOM_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Channel_Widget_EOM_1.setObjectName("Channel_Widget_EOM_1")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.Channel_Widget_EOM_2 = Channel_Widget(self.tab_2)
        self.Channel_Widget_EOM_2.setGeometry(QtCore.QRect(10, 20, 480, 150))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel_Widget_EOM_2.sizePolicy().hasHeightForWidth())
        self.Channel_Widget_EOM_2.setSizePolicy(sizePolicy)
        self.Channel_Widget_EOM_2.setMaximumSize(QtCore.QSize(500, 150))
        self.Channel_Widget_EOM_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Channel_Widget_EOM_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Channel_Widget_EOM_2.setObjectName("Channel_Widget_EOM_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.Channel_Widget_EOM_3 = Channel_Widget(self.tab_3)
        self.Channel_Widget_EOM_3.setGeometry(QtCore.QRect(0, 10, 480, 150))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel_Widget_EOM_3.sizePolicy().hasHeightForWidth())
        self.Channel_Widget_EOM_3.setSizePolicy(sizePolicy)
        self.Channel_Widget_EOM_3.setMaximumSize(QtCore.QSize(500, 150))
        self.Channel_Widget_EOM_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Channel_Widget_EOM_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Channel_Widget_EOM_3.setObjectName("Channel_Widget_EOM_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.toolBox.addItem(self.page_EOM, "")
        self.page_AOM = QtWidgets.QWidget()
        self.page_AOM.setGeometry(QtCore.QRect(0, 0, 541, 209))
        self.page_AOM.setObjectName("page_AOM")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.page_AOM)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 511, 191))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.Channel_Widget_AOM_1 = Channel_Widget(self.tab_4)
        self.Channel_Widget_AOM_1.setGeometry(QtCore.QRect(10, 0, 480, 150))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel_Widget_AOM_1.sizePolicy().hasHeightForWidth())
        self.Channel_Widget_AOM_1.setSizePolicy(sizePolicy)
        self.Channel_Widget_AOM_1.setMaximumSize(QtCore.QSize(500, 150))
        self.Channel_Widget_AOM_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Channel_Widget_AOM_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Channel_Widget_AOM_1.setObjectName("Channel_Widget_AOM_1")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.Channel_Widget_AOM_2 = Channel_Widget(self.tab_5)
        self.Channel_Widget_AOM_2.setGeometry(QtCore.QRect(10, 20, 480, 150))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Channel_Widget_AOM_2.sizePolicy().hasHeightForWidth())
        self.Channel_Widget_AOM_2.setSizePolicy(sizePolicy)
        self.Channel_Widget_AOM_2.setMaximumSize(QtCore.QSize(500, 150))
        self.Channel_Widget_AOM_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Channel_Widget_AOM_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Channel_Widget_AOM_2.setObjectName("Channel_Widget_AOM_2")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.toolBox.addItem(self.page_AOM, "")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(580, 20, 271, 251))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit_address = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_address.setGeometry(QtCore.QRect(80, 19, 171, 25))
        self.lineEdit_address.setObjectName("lineEdit_address")
        self.pushButton_connect = QtWidgets.QPushButton(self.frame)
        self.pushButton_connect.setGeometry(QtCore.QRect(10, 49, 121, 25))
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(17, 20, 54, 17))
        self.label.setObjectName("label")
        self.pushButton_disconnect = QtWidgets.QPushButton(self.frame)
        self.pushButton_disconnect.setGeometry(QtCore.QRect(140, 49, 111, 25))
        self.pushButton_disconnect.setObjectName("pushButton_disconnect")
        self.pushButton_save = QtWidgets.QPushButton(self.frame)
        self.pushButton_save.setGeometry(QtCore.QRect(10, 200, 121, 25))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_load = QtWidgets.QPushButton(self.frame)
        self.pushButton_load.setGeometry(QtCore.QRect(140, 200, 121, 25))
        self.pushButton_load.setObjectName("pushButton_load")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 180, 54, 17))
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(20, 89, 231, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(20, 160, 231, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_set_device = QtWidgets.QPushButton(self.frame)
        self.pushButton_set_device.setGeometry(QtCore.QRect(16, 108, 231, 41))
        self.pushButton_set_device.setObjectName("pushButton_set_device")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 310, 851, 251))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 878, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "EOM 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "EOM 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "EOM 3"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_EOM), _translate("MainWindow", "EOM"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "AOM 1"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "AOM 2"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_AOM), _translate("MainWindow", "AOM"))
        self.pushButton_connect.setText(_translate("MainWindow", "connect"))
        self.label.setText(_translate("MainWindow", "Address:"))
        self.pushButton_disconnect.setText(_translate("MainWindow", "disconnect"))
        self.pushButton_save.setText(_translate("MainWindow", "save"))
        self.pushButton_load.setText(_translate("MainWindow", "load"))
        self.label_2.setText(_translate("MainWindow", "Settings"))
        self.pushButton_set_device.setText(_translate("MainWindow", "Set Device"))

from channel_widget import Channel_Widget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

